---
title: "A—21077—2021—10—26"
author: "by 21077"
output:
  html_document: default
---

## Question
Exercises 3.4, 3.11, and 3.20 (pages 94-96, Statistical Computating with R).

## Answer
```{r include=FALSE}
set.seed(1234)
```

### 3.4

Use acceptance-rejection algorithm to implement Rayleigh.

```{r}
f <- function(x,sigma) x/sigma^2*exp(-x^2/2/sigma^2)

Rayleigh <- function(sigma,n)
{
  g <- function(x) dnorm(x,sd = 2^0.5*sigma)
  rho <- function(x) {
    if(x<=0) return(0)
    f(x,sigma)/g(x)/(8*pi/exp(1))^0.5
  }
  
  ans <- numeric(n)
  for(i in c(1:n)){
    while(TRUE){
      u = runif(1)
      y = rnorm(1,sd = 2^0.5*sigma)
      if(u<=rho(y)) {
        ans[i] <- y
        break
      }
    }
  }
  
  return(ans)  
}

```

```{r}
test <- function(sigma,n=40000){
  x <- Rayleigh(sigma,n)
  hist(x,prob=TRUE,ylim=range(0,1/sigma*exp(-0.5)),main = paste0('sigma=',sigma))
  y <- seq(0,floor(max(x))+1,0.01)
  lines(y,f(y,sigma))
}
```
```{r}
par(mfrow = c(2,2))
test(1)
test(2)
test(5)
test(10)
```



### 3.11

```{r}
mixture <- function(p,n=1000){
  x1 <- rnorm(n)
  x2 <- rnorm(n,mean = 3)
  r <- sample(c(0,1),size = n,replace = TRUE,prob = c(p,1-p))
  x <- x1*(1-r)+x2*r
  return(x)
}
```

```{r}
hist(mixture(0.75,1000),prob = TRUE)
```

```{r}
par(mfrow=c(3,3))
for(p in c(1:9)){
  hist(mixture(p/10,10000),prob = TRUE,main = paste0('p=0.',p,',size=10000'))
}

```

When $p_1=0.5$, the mixture is like bimodal.

### 3.20
```{r}
compound_pois_gamma <- function(t,lambda,a,b,n=1000){
  N <- rpois(n=n,lambda = t*lambda)
  ans <- numeric(n)
  for(i in c(1:n)){
    ans[i] <- sum(rgamma(n=N[i],shape = a,rate = b))
  }
  return(ans)
}
```

```{r}
t <- 10
lambda <- c(1,1,1,1,2,2,2,2)
a <- c(1,1,2,2,1,1,2,2)
b <- c(1,2,1,2,1,2,1,2)
mean_estimate <- numeric(8)
var_estimate <- numeric(8)
for(i in c(1:8)){
  x <- compound_pois_gamma(t,lambda[i],a[i],b[i])
  mean_estimate[i] <- mean(x)
  var_estimate[i] <- var(x)
}

mean_theoretical <- lambda*t*a/b
var_theoretical <- lambda*t*(a+a^2)/b^2

mat <- data.frame(t,lambda,a,b,mean_estimate,mean_theoretical,var_estimate,var_theoretical)
```
```{r}
knitr::kable(mat)
```

 